BEGIN;

CREATE TABLE IF NOT EXISTS public.transport_vehicles (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  description text NOT NULL DEFAULT '',
  vehicle_type text NOT NULL,
  image_path text,
  passenger_capacity integer NOT NULL CHECK (passenger_capacity > 0),
  luggage_capacity integer NOT NULL CHECK (luggage_capacity >= 0),
  price_per_km numeric(12, 2) NOT NULL CHECK (price_per_km >= 0),
  minimum_fare numeric(12, 2) NOT NULL CHECK (minimum_fare >= 0),
  currency char(3) NOT NULL DEFAULT 'USD',
  is_active boolean NOT NULL DEFAULT true,
  display_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.transport_bookings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_reference text NOT NULL UNIQUE,
  idempotency_key uuid NOT NULL UNIQUE,
  user_id integer REFERENCES public.users(id) ON DELETE SET NULL,
  vehicle_id integer NOT NULL REFERENCES public.transport_vehicles(id),
  pickup_at timestamptz NOT NULL,
  origin jsonb NOT NULL,
  destination jsonb NOT NULL,
  distance_km numeric(12, 3) NOT NULL CHECK (distance_km > 0),
  duration_minutes integer NOT NULL CHECK (duration_minutes > 0),
  passengers integer NOT NULL CHECK (passengers > 0),
  luggage integer NOT NULL CHECK (luggage >= 0),
  vehicle_snapshot jsonb NOT NULL,
  price_per_km numeric(12, 2) NOT NULL CHECK (price_per_km >= 0),
  minimum_fare numeric(12, 2) NOT NULL CHECK (minimum_fare >= 0),
  distance_charge numeric(12, 2) NOT NULL CHECK (distance_charge >= 0),
  final_fare numeric(12, 2) NOT NULL CHECK (final_fare >= 0),
  currency char(3) NOT NULL,
  contact jsonb NOT NULL,
  comments text,
  payment_method_reference text,
  payment_method_type text NOT NULL,
  booking_status text NOT NULL DEFAULT 'confirmed' CHECK (booking_status IN ('pending_payment', 'confirmed', 'cancelled')),
  payment_status text NOT NULL DEFAULT 'pay_on_arrival' CHECK (payment_status IN ('pending', 'paid', 'failed', 'pay_on_arrival')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION public.create_transport_booking(
  p_booking_reference text,
  p_idempotency_key uuid,
  p_user_id integer,
  p_vehicle_id integer,
  p_pickup_at timestamptz,
  p_origin jsonb,
  p_destination jsonb,
  p_distance_km numeric,
  p_duration_minutes integer,
  p_passengers integer,
  p_luggage integer,
  p_vehicle_snapshot jsonb,
  p_price_per_km numeric,
  p_minimum_fare numeric,
  p_distance_charge numeric,
  p_final_fare numeric,
  p_currency char(3),
  p_contact jsonb,
  p_comments text,
  p_payment_method_reference text,
  p_payment_method_type text
) RETURNS SETOF public.transport_bookings
LANGUAGE plpgsql AS $$
DECLARE
  v_vehicle public.transport_vehicles%ROWTYPE;
  v_distance_charge numeric(12, 2);
  v_final_fare numeric(12, 2);
BEGIN
  SELECT * INTO v_vehicle
  FROM public.transport_vehicles
  WHERE id = p_vehicle_id
  FOR UPDATE;

  IF NOT FOUND OR NOT v_vehicle.is_active
    OR v_vehicle.passenger_capacity < p_passengers
    OR v_vehicle.luggage_capacity < p_luggage THEN
    RAISE EXCEPTION 'transport_vehicle_unavailable';
  END IF;

  v_distance_charge := round(p_distance_km * v_vehicle.price_per_km, 2);
  v_final_fare := greatest(v_distance_charge, v_vehicle.minimum_fare);

  IF p_price_per_km <> v_vehicle.price_per_km
    OR p_minimum_fare <> v_vehicle.minimum_fare
    OR p_distance_charge <> v_distance_charge
    OR p_final_fare <> v_final_fare
    OR upper(p_currency) <> upper(v_vehicle.currency) THEN
    RAISE EXCEPTION 'transport_quote_stale';
  END IF;

  RETURN QUERY
  INSERT INTO public.transport_bookings (
    booking_reference, idempotency_key, user_id, vehicle_id, pickup_at,
    origin, destination, distance_km, duration_minutes, passengers, luggage,
    vehicle_snapshot, price_per_km, minimum_fare, distance_charge, final_fare,
    currency, contact, comments, payment_method_reference, payment_method_type
  ) VALUES (
    p_booking_reference, p_idempotency_key, p_user_id, p_vehicle_id, p_pickup_at,
    p_origin, p_destination, p_distance_km, p_duration_minutes, p_passengers, p_luggage,
    p_vehicle_snapshot, p_price_per_km, p_minimum_fare, p_distance_charge, p_final_fare,
    p_currency, p_contact, NULLIF(p_comments, ''), p_payment_method_reference, p_payment_method_type
  )
  ON CONFLICT (idempotency_key) DO NOTHING
  RETURNING *;

  IF NOT FOUND THEN
    RETURN QUERY SELECT * FROM public.transport_bookings WHERE idempotency_key = p_idempotency_key;
  END IF;
END;
$$;

INSERT INTO public.transport_vehicles
  (code, name, description, vehicle_type, image_path, passenger_capacity, luggage_capacity, price_per_km, minimum_fare, currency, display_order)
VALUES
  ('jac-sunray', 'JAC Sunray', 'Comfortable private transportation for small groups.', 'Minivan', 'vehicles/jacsunray.jpg', 15, 2, 3.00, 150.00, 'USD', 10),
  ('toyota-hiace', 'Toyota Hiace', 'Spacious air-conditioned minivan for families and birding groups.', 'Minivan', 'vehicles/hiacetb.jpeg', 12, 8, 2.50, 95.00, 'USD', 20),
  ('toyota-hiace-top-roof', 'Toyota Hiace Top Roof', 'High-roof minivan with generous seating and luggage capacity.', 'Minivan', 'vehicles/hiaceht.jpg', 15, 15, 3.50, 160.00, 'USD', 30)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  vehicle_type = EXCLUDED.vehicle_type,
  image_path = EXCLUDED.image_path,
  passenger_capacity = EXCLUDED.passenger_capacity,
  luggage_capacity = EXCLUDED.luggage_capacity,
  price_per_km = EXCLUDED.price_per_km,
  minimum_fare = EXCLUDED.minimum_fare,
  currency = EXCLUDED.currency,
  display_order = EXCLUDED.display_order,
  updated_at = now();

COMMIT;
