const DEFAULT_CURRENCY = 'USD';

const TRANSPORTATION_OPTIONS = {
  SHARED_SHUTTLE: 'shared_shuttle',
  PRIVATE_TRANSFER: 'private_transfer',
};

const TRANSPORTATION_LABELS = {
  [TRANSPORTATION_OPTIONS.SHARED_SHUTTLE]: 'Shared shuttle',
  [TRANSPORTATION_OPTIONS.PRIVATE_TRANSFER]: 'Private transfer',
};

const ALLOWED_TRANSPORTATION_OPTIONS = Object.values(TRANSPORTATION_OPTIONS);

export {
  ALLOWED_TRANSPORTATION_OPTIONS,
  DEFAULT_CURRENCY,
  TRANSPORTATION_LABELS,
  TRANSPORTATION_OPTIONS,
};
