const DEFAULT_CURRENCY = 'USD';

const TRANSFER_OPTIONS = {
  SHARED_SHUTTLE: 'shared_shuttle',
  PRIVATE_TRANSFER: 'private_transfer',
};

const TRANSFER_LABELS = {
  [TRANSFER_OPTIONS.SHARED_SHUTTLE]: 'Shared shuttle',
  [TRANSFER_OPTIONS.PRIVATE_TRANSFER]: 'Private transfer',
};

const ALLOWED_TRANSFER_OPTIONS = Object.values(TRANSFER_OPTIONS);

export {
  ALLOWED_TRANSFER_OPTIONS,
  DEFAULT_CURRENCY,
  TRANSFER_LABELS,
  TRANSFER_OPTIONS,
};
