const TASK_CATEGORIES = Object.freeze([
  'intent_classification',
  'general_chat',
  'rag_answer',
  'tour_recommendation',
  'reservation_planning',
  'tool_selection',
  'bird_image_analysis',
  'evaluation',
]);

const TASK_CATEGORY_SET = new Set(TASK_CATEGORIES);

const MODEL_POLICIES = Object.freeze({
  intent_classification: Object.freeze({
    tier: 'economy',
    reasoningEffort: 'low',
    latencyPriority: 'high',
    requiresVision: false,
    requiresStructuredOutput: true,
    requiresToolCalling: false,
    structuralReliability: 'medium',
    preferredStrength: 'classification',
    timeoutMs: 8000,
    maxRetries: 1,
    reasonCode: 'FAST_INTENT_CLASSIFICATION',
    reason: 'Fast, low-cost intent classification',
  }),
  general_chat: Object.freeze({
    tier: 'balanced',
    reasoningEffort: 'low',
    latencyPriority: 'medium',
    requiresVision: false,
    requiresStructuredOutput: false,
    requiresToolCalling: false,
    structuralReliability: 'medium',
    preferredStrength: 'general',
    timeoutMs: 20000,
    maxRetries: 2,
    reasonCode: 'BALANCED_CONVERSATION',
    reason: 'Balanced conversational quality, cost, and latency',
  }),
  rag_answer: Object.freeze({
    tier: 'balanced',
    reasoningEffort: 'medium',
    latencyPriority: 'medium',
    requiresVision: false,
    requiresStructuredOutput: false,
    requiresToolCalling: false,
    structuralReliability: 'high',
    preferredStrength: 'grounded',
    timeoutMs: 25000,
    maxRetries: 2,
    reasonCode: 'GROUNDED_RAG_RESPONSE',
    reason: 'Consistent grounded response generation',
  }),
  tour_recommendation: Object.freeze({
    tier: 'balanced',
    reasoningEffort: 'medium',
    latencyPriority: 'medium',
    requiresVision: false,
    requiresStructuredOutput: true,
    requiresToolCalling: false,
    structuralReliability: 'high',
    preferredStrength: 'structured',
    timeoutMs: 25000,
    maxRetries: 2,
    reasonCode: 'STRUCTURED_TOUR_RECOMMENDATION',
    reason: 'Reliable structured tour recommendations',
  }),
  reservation_planning: Object.freeze({
    tier: 'advanced',
    reasoningEffort: 'medium',
    latencyPriority: 'low',
    requiresVision: false,
    requiresStructuredOutput: true,
    requiresToolCalling: true,
    structuralReliability: 'high',
    preferredStrength: 'reasoning',
    timeoutMs: 30000,
    maxRetries: 2,
    reasonCode: 'MULTI_STEP_RESERVATION',
    reason: 'Multi-step reservation workflow',
  }),
  tool_selection: Object.freeze({
    tier: 'balanced',
    reasoningEffort: 'medium',
    latencyPriority: 'medium',
    requiresVision: false,
    requiresStructuredOutput: true,
    requiresToolCalling: true,
    structuralReliability: 'high',
    preferredStrength: 'tools',
    timeoutMs: 25000,
    maxRetries: 2,
    reasonCode: 'RELIABLE_TOOL_SELECTION',
    reason: 'Reliable tool calling and structured decisions',
  }),
  bird_image_analysis: Object.freeze({
    tier: 'advanced',
    reasoningEffort: 'medium',
    latencyPriority: 'low',
    requiresVision: true,
    requiresStructuredOutput: true,
    requiresToolCalling: false,
    structuralReliability: 'high',
    preferredStrength: 'vision',
    timeoutMs: 45000,
    maxRetries: 2,
    reasonCode: 'MULTIMODAL_BIRD_ANALYSIS',
    reason: 'Vision-capable structured bird analysis',
  }),
  evaluation: Object.freeze({
    tier: 'advanced',
    reasoningEffort: 'high',
    latencyPriority: 'low',
    requiresVision: false,
    requiresStructuredOutput: true,
    requiresToolCalling: false,
    structuralReliability: 'high',
    requiresEvaluationModel: true,
    preferredStrength: 'evaluation',
    timeoutMs: 60000,
    maxRetries: 1,
    reasonCode: 'INDEPENDENT_EVALUATION',
    reason: 'Independent high-reliability evaluation',
  }),
});

export {
  MODEL_POLICIES,
  TASK_CATEGORIES,
  TASK_CATEGORY_SET,
};
