export const BIRD_IMAGE_ANALYSIS_RESPONSE_SCHEMA = {
  type: 'object',
  additionalProperties: false,
  required: [
    'dominantColors',
    'fieldMarks',
    'bill',
    'head',
    'throat',
    'underparts',
    'upperparts',
    'wings',
    'tail',
    'legs',
    'bodyShape',
    'apparentGroup',
    'habitatHint',
    'imageQuality',
    'confidence',
  ],
  properties: {
    dominantColors: {
      type: 'array',
      minItems: 0,
      maxItems: 8,
      items: { type: 'string' },
    },
    fieldMarks: {
      type: 'array',
      minItems: 0,
      maxItems: 12,
      items: { type: 'string' },
    },
    bill: {
      type: 'object',
      additionalProperties: false,
      required: ['color', 'shape', 'length'],
      properties: {
        color: { type: 'string' },
        shape: { type: 'string' },
        length: { type: 'string' },
      },
    },
    head: { type: 'string' },
    throat: { type: 'string' },
    underparts: { type: 'string' },
    upperparts: { type: 'string' },
    wings: { type: 'string' },
    tail: { type: 'string' },
    legs: { type: 'string' },
    bodyShape: { type: 'string' },
    apparentGroup: { type: 'string' },
    habitatHint: { type: 'string' },
    imageQuality: { type: 'string' },
    confidence: {
      type: 'number',
      minimum: 0,
      maximum: 1,
    },
  },
};
